version: '3'
services:
  test-server:                        # 前端node容器(运行nginx中的Vue项目)
    restart: always                     # 重启策略: 容器退出时总是重启容器
    build:
      context: ./                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: ./Dockerfile
    container_name: test-server-server-container
    environment:
      TZ: Asia/Shanghai
    ports:
      - "2001:3000"                      # 映射端口
