name: Deploy For Dev
on:
  push:
    branches:
      - 'dev' # 只针对 dev 分支
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'bin/*'
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Set SSH Key
        run: |
              mkdir -p ~/.ssh/
              echo "${{ secrets.SSH_WORK_WIN_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan "${{ secrets.IP }}" >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
             ssh work@${{ secrets.IP }} "bash -s" < bin/deploy-dev.sh

      - name: Delete SSH Key
        run: rm -rf ~/.ssh/id_rsa
    